import { RuntimeAdapter } from './runtime-adapter.js';
import { productError, recoveryKey, conciseConfidence, verificationCopy } from './workflow.js';
import { isLiveReference, logicalMicrophones, sourceIdentity, currentSourceFrame, perceptionPresentation, adjustmentHintPresentation, referenceReprepareRequired, capturePresentation, liveReferenceView, LEGACY_RECEIPT_MAX_AGE_MS, receiptMaxAgeMs, analysisTimingPresentation, referenceComparisonPresentation, HintDeadlineTracker, SnapshotClockTracker, FrameResultDeadlineTracker } from './live-reference.js';
import { SessionDeletion } from './session-deletion.js';

const FIXTURE_PATH = '../../contracts/examples/pa_shared_v1.json';
const CATALOG_KEY = 'pa-controller-demo-session-catalog-v1';
export const RECEIPT_FRESHNESS_MAX_MS = LEGACY_RECEIPT_MAX_AGE_MS;
export const SETUP_ENDPOINT_PLAN = ['POST /v1/projects','POST /v1/songs','POST /v1/audio-assets','POST /v1/songs/{id}/reference','GET /v1/jobs/{id}','POST /v1/sessions'];

let runtimeAdapter=null, runtimeHealth=null, runtimeStartupError=null, deviceDiscovery=null, snapshot=null, fixtures=null;
let viewMode='fixture', runtimeConnected=false, runtimeConnectionState='disconnected', receiptMs=null, lastFrameId=null, lastSessionId=null;
let page='selection', setupRows=[['guitar',2],['vocals',1],['bass',1],['drums',1],['keys',0]];
let configuredInstances=[], probePlan=[], probeIndex=-1, probePhase='idle', probeTimer=null, freshnessTimer=null, restoredProbeStep=null;
let evidenceHistory=[], fixtureLiveMode='normal', calibrationDraft=null, operationStatus=null, setupProgress=null;
let pendingCommand=false, setupBusy=false, technicalDetail=null, acknowledgedRecovery=null, verificationRequestedFor=null;
let reviewedFrame=null;
let microphoneChoice=null, sourceSwitchPending=null;
const sessionDeletion=new SessionDeletion();
const referencePreparations=new Map();
const hintDeadlines=new HintDeadlineTracker();
const snapshotClocks=new SnapshotClockTracker();
const resultDeadlines=new FrameResultDeadlineTracker();

export function displayStatus(i){if(i.activity==='inactive')return i.confidence.abstained?'Inactive · Abstained':'Inactive';if(i.activity==='unsupported'||i.status==='unsupported')return'Unsupported / Insufficient Evidence';if(i.activity==='unknown'||i.status==='unknown')return'Insufficient Evidence';if(i.confidence.abstained)return'Abstained / Insufficient Evidence';return({normal:'Normal',too_loud:'Too Loud',too_quiet:'Too Quiet'})[i.status]||'Not Observable';}
export function balanceText(i){const ok=!i.confidence.abstained&&i.activity==='active'&&['normal','too_loud','too_quiet'].includes(i.status)&&typeof i.balance_deviation_db==='number';return ok?`${i.balance_deviation_db>=0?'+':''}${i.balance_deviation_db.toFixed(1)} dB`:'Balance unavailable';}
export function freshness(f,now=null){if(!f)return'No observation received';if(f.quality.stale)return f.example_only?'Stale fixture frame — do not act':'Stale frame — do not act';if(typeof now!=='number')return f.example_only?'Fixture/static frame — data age unavailable':'Data age unavailable';return`${Math.max(0,now-f.published_monotonic_s).toFixed(1)} s old`;}
export function receiptFreshness(f,at,connected,maxAgeMs=RECEIPT_FRESHNESS_MAX_MS,resultDeadlineMs=undefined,now=Date.now()){if(!f)return'No observation received';if(f.quality.stale)return'Stale frame — controls gated';if(!connected||at===null)return'Data freshness unknown — controls gated';const age=Math.max(0,now-at);if(resultDeadlineMs!==undefined&&(!Number.isFinite(resultDeadlineMs)||now>=resultDeadlineMs))return'Observation age budget expired — controls gated';return age>maxAgeMs?`Local receipt age ${(age/1000).toFixed(1)} s — controls gated`:`Received ${(age/1000).toFixed(1)} s ago (local receipt age)`;}
export function receiptIsFresh(f,at,connected,now=Date.now(),maxAgeMs=RECEIPT_FRESHNESS_MAX_MS,resultDeadlineMs=undefined){return Boolean(f)&&!f.quality.stale&&connected&&at!==null&&now-at<=maxAgeMs&&(resultDeadlineMs===undefined||(Number.isFinite(resultDeadlineMs)&&now<resultDeadlineMs));}
export function canMutate(view,adapter,s,connected){return view==='authoritative'&&Boolean(adapter)&&adapter.snapshot?.session_id===s?.session_id&&connected;}
export function commandGuard(action,view,adapter,s,connected,receivedAt,now=Date.now(),resultDeadlineMs=undefined){const bound=view==='authoritative'&&Boolean(adapter)&&adapter.snapshot?.session_id===s?.session_id;if(!bound)return{allowed:false,reason:'The displayed session is not bound to Runtime.'};if(isLiveReference(s)&&['accept_baseline','start_live'].includes(action))return{allowed:false,reason:'This session listens against its uploaded reference.'};if(action==='switch_microphone')return connected&&isLiveReference(s)&&s.capture&&s.song?.workflow_state!=='STOPPED'&&s.capture.state!=='stopped'&&s.capture.switch_result!=='pending'?{allowed:true,reason:null}:{allowed:false,reason:'Wait for the current microphone change or reconnect before trying again.'};if(['pause','stop'].includes(action))return{allowed:true,reason:null};if(action==='resume')return connected?{allowed:true,reason:null}:{allowed:false,reason:'Reconnect to Runtime before resuming.'};if(!canMutate(view,adapter,s,connected))return{allowed:false,reason:'Reconnect to Runtime before sending this action.'};if(isLiveReference(s)&&!currentSourceFrame(s))return{allowed:false,reason:'Wait for fresh current-source audio.'};if(!receiptIsFresh(s?.latest_frame,receivedAt,connected,now,receiptMaxAgeMs(s),resultDeadlineMs))return{allowed:false,reason:'Wait for a fresh authoritative frame before sending this action.'};return{allowed:true,reason:null};}
export function commandFor(s,action,payload={},key=`ui-${action}-fixture`){return{record_type:'SessionCommand',schema_version:'1.0',session_id:s.session_id,idempotency_key:key,expected_state_version:s.state_version,reference:s.active_reference&&{reference_id:s.active_reference.reference_id,source_asset_hash:s.active_reference.source_asset_hash},baseline:s.active_baseline&&{baseline_id:s.active_baseline.baseline_id,baseline_version:s.active_baseline.version},event:s.incident&&{event_id:s.incident.event.event_id,event_version:s.incident.event_version},action,payload};}
export function confidenceText(c){const status=String(c?.calibration_status??'unknown').replaceAll('_',' '),reasons=(c?.reasons??[]).join(', ');if(c?.calibration_status==='uncalibrated')return['Uncalibrated',c.abstained?'Abstained':null,reasons].filter(Boolean).join(' · ');if(c?.abstained)return['Abstained',status,reasons].filter(Boolean).join(' · ');const p=typeof c?.probability==='number'&&c.probability_event?`${Math.round(c.probability*100)}% probability of ${c.probability_event.replaceAll('_',' ')}`:'Probability unavailable',t=typeof c?.magnitude_tolerance_db==='number'?`Magnitude tolerance: ±${c.magnitude_tolerance_db} dB`:null,interval=c?.prediction_interval_db&&`Prediction interval: ${c.prediction_interval_db[0]} to ${c.prediction_interval_db[1]} dB`;return[status,p,t,interval].filter(Boolean).join(' · ');}
export function runtimeReadiness(h,s=null){if(!h)return'Runtime unavailable';const p=s?.execution?.provider??h.provider??'provider unavailable',m=s?.execution?.model_bundle_id??h.model_bundle_id??'model unavailable',x=s?.latest_frame?.example_only??h.example_only;return x===true?`Fake / simulated analyzer · ${p} · ${m}`:x===false?`Real / candidate analyzer · ${p} · ${m}`:`Runtime connected · ${p} · ${m} · analyzer type unavailable`;}
export function modelSupportSummary(s){const configured=s?.song?.configured_families??[];return configured.length?`Configured instrument families · ${configured.join(', ')}`:'Instrument configuration unavailable';}
export function sourcePresentation(s,connected,receivedAt,connectionState='disconnected',now=Date.now(),resultDeadlineMs=undefined){const kind=s?.source?.input_kind==='uploaded_file'?'Uploaded File':'Live Microphone',workflow=s?.song?.workflow_state,reasons=s?.suspension_reasons??[],frame=s?.latest_frame;if(workflow==='ERROR'||reasons.some(reason=>/error|failed|unavailable|device_lost|capture_dropout/.test(reason)))return{kind,state:'error',label:`${kind} · Error`,detail:reasons.join(', ')||'Runtime reported a source error.'};if(workflow==='SUSPENDED')return{kind,state:'suspended',label:`${kind} · Suspended`,detail:reasons.join(', ')||'Source is suspended by Runtime.'};if(connectionState==='connecting')return{kind,state:'connecting',label:`${kind} · Connecting`,detail:'Waiting for the authoritative Runtime event stream.'};if(!connected)return{kind,state:'disconnected',label:`${kind} · Disconnected`,detail:'Runtime event stream is disconnected.'};if(frame&&!receiptIsFresh(frame,receivedAt,connected,now,receiptMaxAgeMs(s),resultDeadlineMs))return{kind,state:'stale',label:`${kind} · Stale`,detail:'The last authoritative frame is too old to use.'};if(!frame)return{kind,state:'connecting',label:`${kind} · Connecting`,detail:'Connected; waiting for the first authoritative frame.'};return{kind,state:'active',label:`${kind} · Active`,detail:'Runtime is publishing authoritative source evidence.'};}
export function referenceProgressText(update){if(!update)return'Reference analysis has not started.';const pct=typeof update.progress==='number'?` · ${Math.round(update.progress*100)}%`:'';return`${update.message??String(update.status??'working').replaceAll('_',' ')}${pct}`;}
export function deviceDiscoveryText(d){if(!d)return'Microphone discovery not requested';const n=Array.isArray(d.devices)?d.devices.length:0;return({available:`${n} native microphone input${n===1?'':'s'} available`,no_input_devices:'No native microphone inputs found',native_backend_unavailable:'Native microphone backend unavailable',injected_example_only:`${n} simulated/injected device ID${n===1?'':'s'} (not physical capture evidence)`,not_connected_in_checkpoint:'Native microphone capture is not connected in this Runtime'})[d.discovery_status]??`Microphone discovery: ${String(d.discovery_status??'unknown').replaceAll('_',' ')}`;}
export function microphoneOptions(devices=[]){const base=devices.map((device,index)=>typeof device.name==='string'&&device.name.trim()?device.name.trim():`Microphone input ${index+1}`),counts=new Map();base.forEach(name=>counts.set(name,(counts.get(name)??0)+1));return devices.map((device,index)=>{const host=counts.get(base[index])>1&&typeof device.host_api==='string'&&device.host_api.trim()?` · ${device.host_api.trim()}`:'';return{device_id:device.device_id,label:`${base[index]}${device.is_default===true?' (Default)':''}${host}`};});}
export function sourceIdentityText(source,discovery){if(source?.input_kind==='uploaded_file')return`uploaded file · ${source.input_asset_or_device_id}`;const option=microphoneOptions(discovery?.devices??[]).find(item=>item.device_id===source?.input_asset_or_device_id);return`live microphone · ${option?.label??'Microphone input'}`;}
export function runtimeErrorText(e){const c=e?.payload?.error?.code;return c==='model_unavailable'?'Runtime model unavailable (HTTP 503); real analysis cannot start.':c?`Runtime unavailable: ${c.replaceAll('_',' ')}.`:'Local Runtime unavailable.';}
export function sessionCondition(s){if(!s)return{label:'No session',detail:'Create or load an authoritative session.'};const w=s.song?.workflow_state??'UNKNOWN';if(w==='SUSPENDED')return{label:'Suspended',detail:(s.suspension_reasons??[]).join(', ')||'No suspension reason supplied.'};if(w==='ERROR')return{label:'Runtime error',detail:'Inspect Runtime diagnostics.'};if(w==='STOPPED')return{label:'Stopped',detail:'Capture is stopped.'};const q=s.latest_frame?.quality;if(q&&(q.dropout||q.stale||q.capture_compatible===false||q.comparability==='unsupported'))return{label:'Unavailable / degraded evidence',detail:(q.reason_codes??[]).join(', ')||'Evidence is not actionable.'};if(!s.latest_frame)return{label:'Waiting for evidence',detail:'Runtime has not published a frame.'};if(s.latest_frame.example_only)return{label:'Simulation evidence only',detail:'Not real-ML or physical-demo evidence.'};return{label:'Authoritative Runtime evidence',detail:'Values come from the active Runtime snapshot.'};}

export function expandInstrumentConfiguration(rows){return rows.flatMap(([family,count])=>Array.from({length:Math.max(0,Number(count)||0)},(_,i)=>({instrument_id:`${family}-${i+1}`,family,display_name:`${family[0].toUpperCase()+family.slice(1)}${count>1?` ${i+1}`:''}`})));}
export function runtimeInstrumentGroups(instances){return[...new Set(instances.map(x=>x.family))].map(family=>({instrument_id:family,family}));}
export function normalizeCatalogRows(value){if(!Array.isArray(value))return[];return value.filter(row=>row&&typeof row.session_id==='string'&&row.session_id&&typeof row.song_name==='string').map(row=>{const counts={};if(row.instrument_counts&&typeof row.instrument_counts==='object'&&!Array.isArray(row.instrument_counts))for(const [family,count] of Object.entries(row.instrument_counts))if(/^[a-z0-9-]+$/.test(family)&&Number.isInteger(count)&&count>0&&count<=32)counts[family]=count;return{session_id:row.session_id,song_name:row.song_name,reference_id:typeof row.reference_id==='string'?row.reference_id:null,baseline_id:typeof row.baseline_id==='string'?row.baseline_id:null,instrument_counts:counts};}).slice(0,12);}
export function restoreConfiguredInstances(families,catalogRow){const counts=catalogRow?.instrument_counts??{};return expandInstrumentConfiguration(families.map(family=>[family,counts[family]??1]));}
export function buildProbePlan(instances){return[...instances.map(x=>({kind:'instrument',id:x.instrument_id,family:x.family,label:`Please play ${x.display_name}`})),{kind:'full_band_quiet',id:'full-band-quiet',label:'Play a quiet / low-intensity passage'},{kind:'full_band_loud',id:'full-band-loud',label:'Play the loudest / highest-intensity passage'},{kind:'review',id:'calibration-review',label:'Calibration review'}];}
export function restoreProbeView(plan,probe){if(!probe||probe.mode==='idle')return null;if(probe.mode==='instrument'){const index=plan.findIndex(step=>step.kind==='instrument'&&step.family===probe.instrument_id);if(index<0)return null;const family=probe.instrument_id[0].toUpperCase()+probe.instrument_id.slice(1);return{index,step:{kind:'instrument',id:probe.probe_id,family:probe.instrument_id,label:`Resume ${family} family probe`,restored:true}};}const index=plan.findIndex(step=>step.kind==='full_band_quiet');return index<0?null:{index,step:{kind:'full_band_restored',id:probe.probe_id,label:'Resume the active full-band probe',restored:true}};}
export function liveEvidenceState(s,receivedAt=undefined,connected=true,now=Date.now(),resultDeadlineMs=undefined){const f=s?.latest_frame;if(!f)return'waiting';if(receivedAt!==undefined&&!receiptIsFresh(f,receivedAt,connected,now,receiptMaxAgeMs(s),resultDeadlineMs))return'unavailable';const q=f.quality??{};if(q.stale||q.dropout||q.capture_compatible===false||['unsupported','not_comparable'].includes(q.comparability))return'unavailable';const instruments=f.instruments??[];if(!instruments.length)return'unavailable';if((s?.song?.unsupported_families??[]).length||instruments.some(i=>i.activity==='unsupported'||i.status==='unsupported'))return'unsupported';if(instruments.some(i=>i.activity==='unknown'||i.status==='unknown'))return'unknown';if(instruments.some(i=>i.activity==='inactive'))return'inactive';if(instruments.some(i=>i.confidence?.abstained))return'abstain';return'observable';}
export function currentRecoveredVerification(s){const v=s?.latest_verification,event=s?.incident?.event;return Boolean(v&&v.outcome==='recovered'&&s.incident_state==='resolved'&&event&&v.event_id===event.event_id&&v.baseline_id===s.active_baseline?.baseline_id&&v.baseline_version===s.active_baseline?.version);}
export function liveViewState(s,receivedAt=undefined,connected=true,now=Date.now(),resultDeadlineMs=undefined){if(!s)return'waiting';if(s.song.workflow_state==='SUSPENDED')return'suspended';const evidence=liveEvidenceState(s,receivedAt,connected,now,resultDeadlineMs);if(evidence==='waiting'||evidence==='unavailable')return evidence;if(['active','adjusting','verifying'].includes(s.incident_state)||s.song.workflow_state==='LIVE_ANOMALY')return'anomaly';if(['unsupported','unknown','inactive','abstain'].includes(evidence))return'abstain';if(currentRecoveredVerification(s))return'recovered';return(s.latest_frame?.instruments??[]).every(i=>i.status==='normal')?'normal':'monitoring';}
export function verificationPresentation(s){const a=s?.adjustment,v=s?.latest_verification;if(a?.completed_monotonic_s&&v?.adjustment_id!==a.adjustment_id)return{state:'waiting',title:'Waiting for fresh verification evidence',detail:'Only evidence captured after the completed adjustment can verify the result.'};if(!v)return null;const title={recovered:'Recovered',partial:'Partially improved',not_recovered:'Not recovered',inconclusive:'Verification inconclusive'}[v.outcome]??'Verification update',reasons=(v.reason_codes??[]).join(', '),values=v.source_observable&&typeof v.before_balance_db==='number'&&typeof v.after_balance_db==='number'?`Before ${v.before_balance_db.toFixed(1)} dB · after ${v.after_balance_db.toFixed(1)} dB`:'';return{state:v.outcome,title,detail:[values,reasons].filter(Boolean).join(' · ')||'Runtime supplied no additional reason.'};}

function makeConfidence(abstained,reasons,prob=.91,event='joint_anomaly_numeric_correct',interval=[2.6,5.6]){return{record_type:'ConfidenceState',schema_version:'1.0',calibration_status:abstained?'out_of_envelope':'calibrated',calibration_id:abstained?null:'fixture-calibration',probability_event:abstained?'not_available':event,magnitude_tolerance_db:1.5,probability:abstained?null:prob,prediction_interval_db:abstained?null:interval,abstained,reasons};}
function showcaseFrame(s,mode='anomaly'){const item=(id,activity,status,d,c)=>({record_type:'InstrumentState',schema_version:'1.0',instrument_id:id,family:id,activity,presence_probability:activity==='active'?.92:null,source_level_delta_db:d,balance_deviation_db:d,status,confidence:c,tone:null});const families=s.song.configured_families;const instruments=families.map((id,i)=>mode==='abstain'?item(id,'unknown','unknown',null,makeConfidence(true,['fixture_low_evidence'])):mode==='anomaly'&&i===0?item(id,'active','too_loud',4.1,makeConfidence(false,[])):item(id,'active','normal',0.2,makeConfidence(false,[],.9,'normal_within_envelope',[-1.3,1.5])));return{record_type:'AnalysisFrame',schema_version:'1.0',example_only:true,frame_id:`fixture-${mode}-${Date.now()}`,session_id:s.session_id,analysis_run_id:'fixture-run',sequence:9,input_kind:s.source.input_kind,input_asset_or_device_id:s.source.input_asset_or_device_id,clock_id:s.source.clock_id,sample_rate_hz:48000,sample_start:2016000,sample_end:2208000,capture_end_monotonic_s:46,published_monotonic_s:47,model_bundle_id:s.execution.model_bundle_id,frontend_id:s.execution.frontend_id,execution_profile_id:s.execution.execution_profile_id,baseline_id:s.active_baseline?.baseline_id??null,baseline_version:s.active_baseline?.version??null,reference_id:s.active_reference.reference_id,quality:{clipped_fraction:0,dropout:false,stale:false,comparability:'comparable',capture_compatible:true,reason_codes:[],snr_estimate_db:null,snr_is_ground_truth:false},observed_mix_level_delta_db:.2,common_mode_gain_db:.1,identifiability_assumption:'majority_active_sources_unchanged',inference_wall_ms:28,instruments};}
export function fixtureScenario(base){const s=structuredClone(base.live_snapshot);s.latest_frame=showcaseFrame(s,'anomaly');s.incident_state='active';s.song.workflow_state='LIVE_ANOMALY';const target={target_kind:'baseline',reference:{reference_id:s.active_reference.reference_id,source_asset_hash:s.active_reference.source_asset_hash},baseline:{baseline_id:s.active_baseline.baseline_id,baseline_version:s.active_baseline.version}};const c=s.latest_frame.instruments[0].confidence,e={record_type:'AnomalyEvent',schema_version:'1.0',event_id:'fixture-event-1',session_id:s.session_id,instrument_ids:[s.latest_frame.instruments[0].instrument_id],direction:'too_loud',onset_monotonic_s:43,confirmed_monotonic_s:46,baseline_id:s.active_baseline.baseline_id,reference_id:s.active_reference.reference_id,evidence_frame_ids:[s.latest_frame.frame_id],state:'active',confidence:c};s.incident={event:e,event_version:1,target};s.recommendations=[{record_type:'Recommendation',schema_version:'1.0',recommendation_id:'fixture-rec',event_id:e.event_id,instrument_id:e.instrument_ids[0],action:'reduce_level',suggested_step_db:-2,human_control_hint:'Make a small manual level correction, then recheck.',message_template_id:'reduce-v1',evidence_frame_ids:[s.latest_frame.frame_id],expires_monotonic_s:60,automatic_execution:false}];return s;}
export function fixtureRehearsal(base){const s=structuredClone(base.rehearsal_snapshot);s.latest_frame=showcaseFrame(s,'normal');return s;}
export function fixtureLiveSnapshot(base,mode,prior=null){const s=['anomaly','recovered'].includes(mode)?fixtureScenario(base):structuredClone(base.live_snapshot);if(mode!=='anomaly')s.latest_frame=showcaseFrame(s,mode==='abstain'?'abstain':'normal');if(prior){s.song={...s.song,...prior.song,workflow_state:'LIVE_MONITORING'};s.active_reference=prior.active_reference??s.active_reference;s.active_baseline=prior.active_baseline??s.active_baseline;s.latest_frame.reference_id=s.active_reference?.reference_id??null;s.latest_frame.baseline_id=s.active_baseline?.baseline_id??null;}s.incident_state=mode==='anomaly'?'active':mode==='recovered'?'resolved':'none';s.song.workflow_state=mode==='anomaly'?'LIVE_ANOMALY':'LIVE_MONITORING';if(mode==='recovered'){s.incident.event.state='resolved';s.recommendations=[];}else if(mode!=='anomaly'){s.incident=null;s.recommendations=[];}s.latest_verification=mode==='recovered'?{record_type:'VerificationResult',schema_version:'1.0',verification_id:'fixture-recovered',event_id:s.incident.event.event_id,adjustment_id:'fixture-adjustment',baseline_id:s.active_baseline.baseline_id,baseline_version:s.active_baseline.version,adjustment_completed_monotonic_s:45,first_evidence_sample_start_monotonic_s:48,evidence_frame_ids:[s.latest_frame.frame_id],instrument_id:s.latest_frame.instruments[0].instrument_id,before_balance_db:4.1,after_balance_db:.2,source_observable:true,outcome:'recovered',reason_codes:[]}:null;return s;}

const app=()=>document.querySelector('#app');
function node(tag,text='',cls=''){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,fn,cls='primary',type='button'){const b=node('button',text,cls);b.type=type;b.addEventListener('click',fn);return b;}
function clearTimer(){clearTimeout(probeTimer);probeTimer=null;}
function clearFreshnessTimer(){clearInterval(freshnessTimer);freshnessTimer=null;}
function ensureFreshnessTimer(){if(freshnessTimer||viewMode!=='authoritative'||page!=='console')return;freshnessTimer=setInterval(()=>{if(viewMode==='authoritative'&&page==='console'&&snapshot)renderConsole();else clearFreshnessTimer();},1000);}
function currentReceiptFresh(now=Date.now()){return receiptIsFresh(snapshot?.latest_frame,receiptMs,runtimeConnected,now,receiptMaxAgeMs(snapshot),resultDeadlines.deadline(snapshot));}
function guardedButton(label,action,payload={},cls='secondary'){const guard=commandGuard(action,viewMode,runtimeAdapter,snapshot,runtimeConnected,receiptMs,Date.now(),resultDeadlines.deadline(snapshot)),b=button(label,()=>sendCommand(action,payload),cls);b.disabled=pendingCommand||!guard.allowed;if(guard.reason)b.title=productError(guard.reason);return b;}
export function calibrationDraftFor(s,previous=null,useLatest=false){const f=s.latest_frame,clock=f?.clock_id??s.source?.clock_id??'',changed=!previous||previous.sessionId!==s.session_id||!previous.run||previous.clock!==clock||(f&&previous.run!==f.analysis_run_id);if(!changed&&!useLatest)return previous;return{sessionId:s.session_id,acceptedBy:previous?.acceptedBy??'operator',clock,run:f?.analysis_run_id??'',rate:f?.sample_rate_hz??null,start:f?.sample_start??null,end:f?.sample_end??null,frameId:f?.frame_id??null,difference:previous?.difference??false};}
function setSnapshot(next){if(viewMode!=='authoritative'||runtimeAdapter?.deletedSessionIds.has(next.session_id))return;const now=Date.now(),switched=sourceIdentity(snapshot)!==sourceIdentity(next),sessionChanged=next.session_id!==lastSessionId;if(sessionChanged||switched){lastSessionId=next.session_id;lastFrameId=null;receiptMs=null;evidenceHistory=[];acknowledgedRecovery=null;verificationRequestedFor=null;microphoneChoice=null;hintDeadlines.reset();snapshotClocks.reset();resultDeadlines.reset();clearTimer();if(sessionChanged)sourceSwitchPending=null;}snapshot=next;if(sourceSwitchPending&&next.capture?.operation_id===sourceSwitchPending.command.idempotency_key&&next.capture.switch_result!=='pending')sourceSwitchPending=null;if(next.latest_frame?.frame_id!==lastFrameId){lastFrameId=next.latest_frame?.frame_id??null;receiptMs=lastFrameId?now:null;}snapshotClocks.update(next,now);resultDeadlines.update(next,now);hintDeadlines.update(next,receiptMs,now);if(page==='console')renderConsole();}
function header(step){const h=node('header','','app-header');h.append(node('div','Harmonix','brand'),node('div',step,'mode-pill'));return h;}
function notice(){const simulated=snapshot?.latest_frame?.example_only??runtimeHealth?.example_only;return node('p',viewMode==='fixture'?'Offline example · illustrative values, not real-model or physical evidence.':simulated===true?'FakeAnalyzer · simulated audio evidence, not physical validation.':simulated===false?'Candidate model · experimental evidence; physical performance is not validated.':'Analysis identity unavailable · not validated evidence.','truth-notice');}
function operationNotice(){if(!operationStatus)return null;const box=node('section','','global-status');box.id='global-status';box.setAttribute('role','status');box.append(node('p',operationStatus));if(technicalDetail)box.append(disclosure('Technical details','error-detail',node('pre',technicalDetail)));return box;}
function appendOperationNotice(root){const message=operationNotice();if(message)root.append(message);}
function updateSetupProgress(update){setupProgress=update;const box=document.querySelector('#setup-progress'),text=document.querySelector('#setup-progress-text'),bar=document.querySelector('#setup-progress-bar');if(!box||!text||!bar)return;box.hidden=false;box.className=`setup-progress ${update.status??'running'}`;text.textContent=referenceProgressText(update);bar.style.setProperty('--progress',`${Math.round((update.progress??(['completed','failed'].includes(update.status)?1:.08))*100)}%`);}
function renderSelection(){page='selection';clearTimer();clearFreshnessTimer();operationStatus=null;technicalDetail=null;if(runtimeAdapter)viewMode='authoritative';const root=app();root.dataset.workflow='HOME';root.replaceChildren(header('LIVE SOUND REFERENCE'));const hero=node('section','','entry-hero');hero.append(node('p','LISTEN · COMPARE · CORRECT · VERIFY','eyebrow'),node('h1','Hear it. Balance it. Play on.','hero-title'),node('p','Your reference. Your room. A balance worth keeping.','hero-copy'),button('Add song',renderSetup,'primary large'));const catalog=getCatalog();if(catalog.length){const list=node('section','','saved-sessions');list.append(node('h2','Recent songs','section-title'));catalog.forEach(x=>list.append(recentSessionRow(x)));hero.append(list);}const form=node('form','','existing-form');form.innerHTML='<label>Session ID<input name="sessionId" required placeholder="session-…"></label><button class="secondary" type="submit">Open session</button>';form.addEventListener('submit',e=>{e.preventDefault();loadSession(new FormData(form).get('sessionId'));});hero.append(disclosure('Connection options','home-connection',form));if(fixtures){const choices=node('div','','live-actions');choices.append(button('Example Live',()=>openFixture(true),'secondary'));hero.append(disclosure('Explore an offline example','home-examples',node('p','Illustrative only. No audio is sent for analysis.','muted'),choices));}root.append(hero,notice());if(runtimeStartupError)showError(runtimeStartupError,'connection');}
function recentSessionRow(row){
  const box=node('div','','saved-session-row'),pending=sessionDeletion.pending.has(row.session_id);
  const open=button('',()=>loadSession(row.session_id),'saved-session-open');
  open.append(node('strong',row.song_name,'saved-session-name'),node('span','Open saved session','saved-session-meta'));open.disabled=pending;
  const remove=button(pending?'Deleting…':'Delete',()=>deleteRecentSession(row),'delete-session');
  remove.setAttribute('aria-label',`Delete session ${row.song_name} (${row.session_id})`);
  remove.disabled=pending||!runtimeAdapter||viewMode!=='authoritative';
  if(remove.disabled&&!pending)remove.title='Connect to Runtime to delete this session.';
  box.append(open,remove);return box;
}
function clearSessionView(id){
  if(viewMode!=='authoritative'||snapshot?.session_id!==id)return;
  snapshot=null;lastSessionId=null;lastFrameId=null;receiptMs=null;evidenceHistory=[];configuredInstances=[];hintDeadlines.reset();snapshotClocks.reset();resultDeadlines.reset();
  microphoneChoice=null;sourceSwitchPending=null;acknowledgedRecovery=null;verificationRequestedFor=null;
  calibrationDraft=null;reviewedFrame=null;restoredProbeStep=null;probePlan=[];probeIndex=-1;probePhase='idle';pendingCommand=false;
  clearTimer();clearFreshnessTimer();if(page==='console')renderSelection();
}
function confirmSessionDeletion(message){
  return new Promise(resolve=>{
    const previousFocus=document.activeElement,dialog=node('dialog','','session-delete-dialog');
    const [heading,...detailParts]=message.split('\n\n');
    const eyebrow=node('p','REMOVE SESSION','eyebrow delete-eyebrow');
    const title=node('h2',heading,'delete-dialog-title');title.id='delete-session-title';
    const details=detailParts.filter(Boolean),copy=node('p',details[0]??'This session’s history will be permanently deleted.','delete-dialog-copy');copy.id='delete-session-description';
    const retained=node('p',details[1]??'Your song and uploaded reference will stay available.','delete-dialog-retained');
    dialog.setAttribute('aria-labelledby',title.id);dialog.setAttribute('aria-describedby',copy.id);
    let settled=false;
    const finish=confirmed=>{if(settled)return;settled=true;dialog.close();dialog.remove();if(previousFocus?.isConnected)previousFocus.focus();resolve(confirmed);};
    const actions=node('div','','delete-dialog-actions'),cancel=button('Keep session',()=>finish(false),'secondary');
    actions.append(cancel,button('Delete session',()=>finish(true),'danger-action'));
    dialog.append(eyebrow,title,copy,retained,actions);dialog.addEventListener('cancel',event=>{event.preventDefault();finish(false);});
    document.body.append(dialog);if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');cancel.focus();
  });
}
async function deleteRecentSession(row){
  try{
    const result=await sessionDeletion.request(row,{adapter:runtimeAdapter,authoritative:viewMode==='authoritative',confirm:confirmSessionDeletion,
      onPending:()=>{if(page==='selection')renderSelection();},onDeleted:id=>{removeCatalog(id);clearSessionView(id);}});
    if(result.deleted&&page==='selection'){renderSelection();statusMessage('Session deleted. Your song and uploaded reference are kept.');}
  }catch(error){
    if(page==='selection')renderSelection();
    technicalDetail=error?.payload?JSON.stringify(error.payload,null,2):String(error?.message??error);
    statusMessage('We couldn’t confirm deletion. The session remains in Recent songs. Check the connection and try again.');
  }
}
function renderSetup(){page='setup';setupProgress=null;operationStatus=null;technicalDetail=null;clearFreshnessTimer();const root=app();root.dataset.workflow='SONG_SETUP';root.replaceChildren(header('SONG SETUP'));const form=node('form','','setup-layout');const ref=node('section','','panel setup-panel');ref.innerHTML='<p class="eyebrow">REFERENCE</p><h1 class="setup-title">Prepare the song</h1><label>Song name<input name="song" value="Example song" required></label><label>Reference audio (PCM16 WAV)<input name="reference" type="file" accept=".wav,audio/wav" required></label><details class="secondary-details"><summary>Project details</summary><label>Project<input name="project" value="Demo set" required></label></details><label>Listen through<select name="source" id="setup-source"><option value="live_microphone">Live Microphone</option><option value="uploaded_file">Uploaded File (reference replay)</option></select></label><label id="setup-device-row">Microphone input<select name="sourceId" id="setup-device"></select></label><p class="muted" id="source-copy"></p><p class="muted" id="device-copy"></p><section id="setup-progress" class="setup-progress" hidden><p id="setup-progress-text"></p><div class="setup-progress-track"><span id="setup-progress-bar"></span></div></section>';
const instruments=node('section','','panel setup-panel');instruments.append(node('p','WHO IS PLAYING?','eyebrow'),node('p','Add the performers for this song. Instruments are assessed by family. Recognition may remain uncertain; adding a family does not validate its identification.','muted'));const list=node('div','','quantity-list');const draw=()=>{list.replaceChildren(...setupRows.map(([family,count],idx)=>{const r=node('div','','quantity-row');r.append(node('strong',family[0].toUpperCase()+family.slice(1)),button('−',()=>{setupRows[idx][1]=Math.max(0,count-1);draw();},'count'),node('span',String(count),'quantity'),button('+',()=>{setupRows[idx][1]=count+1;draw();},'count'));r.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-label',`${i?'Add':'Remove'} ${family} performer`));return r;}));};draw();const add=node('div','','add-instrument');add.innerHTML='<input aria-label="New instrument family" placeholder="Add instrument"><button type="button" class="secondary">Add instrument</button>';add.querySelector('button').onclick=()=>{const v=add.querySelector('input').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-');if(v&&!setupRows.some(x=>x[0]===v)){setupRows.push([v,1]);draw();add.querySelector('input').value='';}};instruments.append(list,disclosure('Other instrument families','other-families',add));const actions=node('div','','setup-actions');actions.append(button('Back',renderSelection,'ghost'),button('Prepare reference',()=>{},'primary','submit'));form.append(ref,instruments,actions);form.addEventListener('submit',async e=>{e.preventDefault();await createSong(new FormData(form));});root.append(form,notice());appendOperationNotice(root);populateDeviceSelect();const source=document.querySelector('#setup-source');source.addEventListener('change',syncSetupSource);syncSetupSource();}
function syncSetupSource(){const source=document.querySelector('#setup-source'),row=document.querySelector('#setup-device-row'),select=document.querySelector('#setup-device'),copy=document.querySelector('#source-copy'),deviceCopy=document.querySelector('#device-copy');if(!source||!row||!select||!copy)return;const live=source.value==='live_microphone',submit=document.querySelector('.setup-actions [type="submit"]');if(submit)submit.disabled=!runtimeAdapter;row.hidden=!live;if(deviceCopy)deviceCopy.hidden=!live;select.disabled=!live||!logicalMicrophones(deviceDiscovery).length;select.required=false;copy.textContent=live?'Listen against your reference. You can change microphone at any time.':'Replay the uploaded reference through the same analysis pipeline.';}
function populateDeviceSelect(){const s=document.querySelector('#setup-device'),copy=document.querySelector('#device-copy');if(!s)return;const options=logicalMicrophones(deviceDiscovery);s.replaceChildren(...options.map(item=>{const o=node('option',item.label);o.value=item.id;return o;}));if(deviceDiscovery?.default_microphone_id)s.value=deviceDiscovery.default_microphone_id;if(!options.length){const o=node('option','System default — waiting for microphone');o.value='';s.append(o);}copy.textContent=deviceDiscovery?.discovery_status==='injected_example_only'?'Simulated input — not physical microphone evidence.':options.length?'Choose a microphone by name.':'You can prepare the song now and connect a microphone later.';syncSetupSource();}
async function createSong(data){if(setupBusy)return;configuredInstances=expandInstrumentConfiguration(setupRows);const groups=runtimeInstrumentGroups(configuredInstances),source=data.get('source');if(!groups.length)return statusMessage('Add at least one instrument.');if(!runtimeAdapter||viewMode!=='authoritative')return statusMessage('Connect the listening service to prepare a song. Offline examples are available from Home.');const file=data.get('reference'),sourceId=source==='uploaded_file'?'reference-asset':data.get('sourceId');if(!(file instanceof File)||!file.size)return statusMessage('Choose a PCM16 WAV reference.');restoredProbeStep=null;setupBusy=true;operationStatus=null;technicalDetail=null;const form=document.querySelector('.setup-layout');form.hidden=true;document.querySelector('#global-status')?.remove();const progress=node('section','','preparation-focus');progress.id='preparation-focus';progress.innerHTML='<p class="eyebrow">REFERENCE PREPARATION</p><h1 class="panel-title">Preparing your reference…</h1><p>Keep this page open. Listening will begin when the reference is ready.</p>';const progressBox=document.querySelector('#setup-progress');progress.append(progressBox);app().append(progress);try{await runtimeAdapter.setupLiveReference({project:data.get('project'),song:data.get('song'),families:groups.map(x=>x.family),reference:file,source,sourceId,onProgress:updateSetupProgress});operationStatus=null;page='console';renderConsole();saveCatalog(snapshot);}catch(e){form.hidden=false;progress.remove();form.querySelector('.setup-panel').append(progressBox);progressBox.hidden=true;showError(e,'reference');}finally{setupBusy=false;}}
function statusMessage(text){operationStatus=text;document.querySelector('#global-status')?.remove();appendOperationNotice(app());}
function showError(error,context='action'){technicalDetail=error?.payload?JSON.stringify({status:error.status,payload:error.payload},null,2):String(error?.message??error);statusMessage(productError(error,context));}
function disclosure(title,id,...children){const d=node('details','','secondary-details');d.id=id;d.append(node('summary',title),...children);return d;}
async function loadSession(id){if(!runtimeAdapter)return statusMessage('Connect the listening service or use the offline example.');const sessionId=String(id);try{viewMode='authoritative';runtimeStartupError=null;const catalogRow=getCatalog().find(row=>row.session_id===sessionId);await runtimeAdapter.openSession(sessionId);if(runtimeAdapter.activeSessionId!==sessionId||runtimeAdapter.deletedSessionIds.has(sessionId))return;configuredInstances=restoreConfiguredInstances(snapshot?.song.configured_families??[],catalogRow);operationStatus=null;page='console';microphoneChoice=null;saveCatalog(snapshot);renderConsole();}catch(e){if(!runtimeAdapter.deletedSessionIds.has(sessionId))showError(e);}}
function openFixture(){runtimeAdapter?.stopEvents();clearFreshnessTimer();hintDeadlines.reset();snapshotClocks.reset();resultDeadlines.reset();viewMode='fixture';runtimeConnected=false;operationStatus=null;sourceSwitchPending=null;acknowledgedRecovery=null;verificationRequestedFor=null;snapshot=fixtureReferenceSnapshot(fixtures,'normal');page='console';renderConsole();}
function fixtureReferenceSnapshot(base,mode){const s=fixtureLiveSnapshot(base,mode);s.workflow_policy='live_reference_v1';s.active_baseline=null;s.song.baseline_id=null;s.latest_frame.baseline_id=null;s.latest_frame.baseline_version=null;s.capture={requested_microphone_id:null,state:'active',source_generation:0,logical_microphone_id:'example-input',name:'Illustrative input',native_device_id:null,clock_id:s.source.clock_id,analysis_run_id:s.latest_frame.analysis_run_id,frame_fresh:true,timestamp_mode:'sample_count',operation_id:null,switch_result:'none',reason_codes:[]};s.perception=s.latest_frame.instruments.map(i=>({instrument_id:i.instrument_id,family:i.family,state:mode==='abstain'?'uncertain':mode==='unsupported'?'unsupported':'detected',frame_id:s.latest_frame.frame_id,reason_codes:['illustrative_example'],activity:mode==='unsupported'?'unsupported':'active',observability:'observable',validity:'valid',calibration_status:mode==='uncalibrated'?'uncalibrated':'calibrated',action_abstained:['abstain','uncalibrated','unsupported'].includes(mode),numerical_advice_allowed:!['abstain','uncalibrated','unsupported'].includes(mode)}));if(['uncalibrated','unsupported'].includes(mode)){for(const i of s.latest_frame.instruments){i.status=mode==='unsupported'?'unsupported':'unknown';i.activity=mode==='unsupported'?'unsupported':'active';i.balance_deviation_db=null;i.source_level_delta_db=null;i.presence_probability=null;i.confidence={...i.confidence,calibration_status:'uncalibrated',calibration_id:null,probability:null,prediction_interval_db:null,probability_event:'not_available',abstained:true,reasons:['illustrative_example']};}}if(s.incident){s.incident.target={target_kind:'reference',reference:{reference_id:s.active_reference.reference_id,source_asset_hash:s.active_reference.source_asset_hash},baseline:null};s.incident.event.baseline_id=null;}if(s.latest_verification){s.latest_verification.baseline_id=null;s.latest_verification.baseline_version=null;}return s;}
function saveCatalog(s){if(!s||viewMode!=='authoritative'||typeof localStorage==='undefined'||runtimeAdapter?.deletedSessionIds.has(s.session_id))return false;try{const rows=getCatalog().filter(x=>x.session_id!==s.session_id),instrument_counts={};for(const item of configuredInstances)instrument_counts[item.family]=(instrument_counts[item.family]??0)+1;rows.unshift({session_id:s.session_id,song_name:s.song.name,reference_id:s.active_reference?.reference_id??null,baseline_id:s.active_baseline?.baseline_id??null,instrument_counts});localStorage.setItem(CATALOG_KEY,JSON.stringify(normalizeCatalogRows(rows)));return true;}catch{return false;}}
function removeCatalog(id){if(typeof localStorage==='undefined')return false;try{localStorage.setItem(CATALOG_KEY,JSON.stringify(getCatalog().filter(x=>x.session_id!==id)));return true;}catch{return false;}}
function renderSourceStatus(){const now=Date.now(),value=viewMode==='fixture'?{title:'Offline example',detail:'Illustrative audio states only.'}:capturePresentation(snapshot,deviceDiscovery,{connected:runtimeConnected,fresh:currentReceiptFresh(now),switchPending:Boolean(sourceSwitchPending)}),box=node('section','',`source-status ${snapshot.capture?.state??'unavailable'}`);box.append(node('strong',value.title),node('span',value.detail,'muted'));if(viewMode==='authoritative'&&snapshot.latest_frame){const timing=analysisTimingPresentation(snapshot,snapshotClocks.anchor(snapshot),now,receiptMs);if(timing)box.append(node('span',timing.observation,'muted'),node('span',timing.processing,'muted'),node('span',timing.receipt,'muted'));}return box;}
function renderModelStatus(){const box=node('section','','model-status');box.append(node('span',runtimeReadiness(runtimeHealth,snapshot),'model-identity'),node('span',modelSupportSummary(snapshot),'model-support'),node('span','Configuration does not establish model support. Current states and advice require reliable evidence.','muted'));return box;}
function renderConsole(){
  if(!snapshot)return renderSelection();page='console';ensureFreshnessTimer();if(!isLiveReference(snapshot))return renderLegacySession();
  const root=app(),openIds=[...root.querySelectorAll('details[open]')].map(d=>d.id),focusButton=document.activeElement?.tagName==='BUTTON'?document.activeElement.textContent:null;
  const connected=viewMode==='fixture'||runtimeConnected,fresh=viewMode==='fixture'||currentReceiptFresh();
  const recovered=recoveryKey(snapshot),boundRecovery=recovered?`${sourceIdentity(snapshot)}:${recovered}`:null;
  const state=liveReferenceView(snapshot,{connected,fresh,switchPending:Boolean(sourceSwitchPending),acknowledgedRecovery,recoveredKey:boundRecovery}),changed=root.dataset.workflow!==state;root.dataset.workflow=state;
  if(!document.getElementById('live-shell-body')){const head=node('div'),input=node('div'),body=node('div'),foot=node('div');head.id='live-shell-header';input.id='live-shell-input';body.id='live-shell-body';foot.id='live-shell-footer';root.replaceChildren(head,input,body,foot);input.append(renderMicrophoneSelector());}
  const head=document.getElementById('live-shell-header'),body=document.getElementById('live-shell-body'),foot=document.getElementById('live-shell-footer');
  const songHead=node('section','','song-header');songHead.append(node('h1',snapshot.song.name,'song-title'),button('Songs',renderSelection,'ghost'));head.replaceChildren(header('LIVE · REFERENCE'),songHead,notice());
  updateMicrophoneSelector();body.replaceChildren(renderSourceStatus(),renderReferenceSummary());
  if(state==='INTERRUPTED')renderInterrupted(body);else if(['LIVE_ANOMALY','VERIFYING','RECOVERED'].includes(state))renderActionState(body,state);else renderLive(body);
  foot.replaceChildren(disclosure('Session options','session-options',renderSessionControls()),disclosure('Technical details','model-details',renderModelStatus(),renderRuntimeStrip(),node('pre',JSON.stringify({capture:snapshot.capture,perception:snapshot.perception,quality:snapshot.latest_frame?.quality,confidence:snapshot.latest_frame?.instruments?.map(i=>({family:i.family,...i.confidence}))},null,2))));
  if(viewMode==='fixture'){const choices=node('div','','live-actions');['normal','anomaly','abstain','uncalibrated','unsupported','recovered'].forEach(mode=>choices.append(button(mode,()=>{acknowledgedRecovery=null;snapshot=fixtureReferenceSnapshot(fixtures,mode);renderConsole();},'secondary')));foot.append(disclosure('Offline example controls','fixture-controls',choices));}
  appendOperationNotice(foot);openIds.forEach(id=>{const d=document.getElementById(id);if(d)d.open=true;});if(focusButton)[...root.querySelectorAll('button')].find(b=>b.textContent===focusButton&&!b.disabled)?.focus({preventScroll:true});if(changed&&document.activeElement?.id!=='session-microphone')window.scrollTo({top:0,behavior:'instant'});
}
function renderMicrophoneSelector(){
  const box=node('section','','microphone-picker');box.innerHTML='<label for="session-microphone">Microphone</label><select id="session-microphone"></select>';
  box.querySelector('select').addEventListener('change',e=>{microphoneChoice=e.target.value;updateMicrophoneSelector();});
  const apply=button('Use microphone',()=>submitMicrophoneSwitch(),'secondary');apply.id='switch-microphone';
  const refresh=button('Refresh microphones',refreshMicrophones,'ghost');refresh.id='refresh-microphones';box.append(apply,refresh);return box;
}
function updateMicrophoneSelector(){
  const select=document.getElementById('session-microphone'),apply=document.getElementById('switch-microphone');if(!select||!apply)return;
  const options=logicalMicrophones(deviceDiscovery),signature=JSON.stringify(options);
  if(select.dataset.inventory!==signature){select.replaceChildren(...options.map(item=>{const o=node('option',item.label);o.value=item.id;return o;}));select.dataset.inventory=signature;}
  const desired=microphoneChoice??sourceSwitchPending?.requested??(snapshot.capture?.switch_result==='pending'?snapshot.capture.requested_microphone_id:snapshot.capture?.logical_microphone_id)??deviceDiscovery?.default_microphone_id;
  if(desired&&options.some(o=>o.id===desired))select.value=desired;else if(!microphoneChoice){select.value='';}
  const pending=Boolean(sourceSwitchPending)||snapshot.capture?.switch_result==='pending',stopped=snapshot.song.workflow_state==='STOPPED'||snapshot.capture?.state==='stopped';
  select.disabled=viewMode!=='authoritative'||pending||stopped||!options.length;
  document.getElementById('refresh-microphones').disabled=viewMode!=='authoritative'||!runtimeAdapter;
  apply.textContent=sourceSwitchPending?.retry?'Retry microphone change':pending?'Changing microphone…':'Use microphone';
  apply.disabled=viewMode!=='authoritative'||!runtimeConnected||pendingCommand||stopped||(!sourceSwitchPending?.retry&&(pending||!select.value));
  if(!select.options.length){const o=node('option',viewMode==='fixture'?'Offline example — no microphone control':'No microphone found');o.value='';select.append(o);}
}
async function refreshMicrophones(){if(!runtimeAdapter||viewMode!=='authoritative')return;try{deviceDiscovery=await runtimeAdapter.audioDevices();updateMicrophoneSelector();}catch(e){showError(e,'connection');}}
async function submitMicrophoneSwitch(){
  if(pendingCommand||viewMode!=='authoritative')return;
  let c=sourceSwitchPending?.retry?sourceSwitchPending.command:null;
  if(!c){const guard=commandGuard('switch_microphone',viewMode,runtimeAdapter,snapshot,runtimeConnected,receiptMs,Date.now(),resultDeadlines.deadline(snapshot));if(!guard.allowed)return statusMessage(productError(guard.reason));const id=document.getElementById('session-microphone').value;if(!id)return;c=commandFor(snapshot,'switch_microphone',{microphone_id:id,expected_source_generation:snapshot.capture.source_generation},`ui-microphone-${crypto.randomUUID()}`);}
  if(c.session_id!==snapshot.session_id)return;
  sourceSwitchPending={command:c,requested:c.payload.microphone_id,retry:false};microphoneChoice=null;pendingCommand=true;operationStatus=null;technicalDetail=null;renderConsole();
  try{await runtimeAdapter.command(c);if(snapshot?.session_id===c.session_id&&viewMode==='authoritative')sourceSwitchPending=null;}catch(e){if(snapshot?.session_id===c.session_id&&viewMode==='authoritative'){if(e.status)sourceSwitchPending=null;else sourceSwitchPending={command:c,requested:c.payload.microphone_id,retry:true};showError(e);}}finally{pendingCommand=false;if(page==='console')renderConsole();}
}
function renderLegacySession(){const root=app();root.dataset.workflow='LEGACY';root.replaceChildren(header('SAVED SONG'));const box=node('section','','task-focus');box.append(node('h1',snapshot.song.name,'panel-title'),node('p','This is a legacy session. Its baseline and history will not be changed. Open a new session to listen against the existing uploaded reference.','hero-copy'));if(snapshot.song?.song_id&&snapshot.active_reference?.reference_id)box.append(button('Listen with this reference',openReferenceSession,'primary'));box.append(button('Songs',renderSelection,'secondary'));root.append(box,notice());appendOperationNotice(root);}
async function openReferenceSession(){if(pendingCommand)return;pendingCommand=true;const previous=snapshot;try{await runtimeAdapter.createLiveReferenceSession({song_id:previous.song.song_id,reference_id:previous.active_reference.reference_id});operationStatus=null;saveCatalog(snapshot);renderConsole();}catch(e){showError(e);}finally{pendingCommand=false;}}
function renderRuntimeStrip(){const s=node('section','','runtime-strip'),baseline=snapshot.active_baseline?`${snapshot.active_baseline.baseline_id} v${snapshot.active_baseline.version}`:'none accepted';s.append(node('span',`session ${snapshot.session_id}`),node('span',`reference ${snapshot.active_reference?.reference_id??'none'}`),node('span',`baseline ${baseline}`),node('span',sourceIdentityText(snapshot.source,deviceDiscovery)),node('span',`${snapshot.execution.provider} · ${snapshot.execution.model_bundle_id}`),node('span',viewMode==='authoritative'?receiptFreshness(snapshot.latest_frame,receiptMs,runtimeConnected,receiptMaxAgeMs(snapshot),resultDeadlines.deadline(snapshot)):freshness(snapshot.latest_frame)));return s;}
function renderReferenceSummary(){
  const box=node('section','','reference-summary');
  box.append(node('p','REFERENCE','eyebrow'),node('strong','Uploaded reference','reference-title'),node('span','The fixed comparison target for this song.','muted'));
  const comparison=referenceComparisonPresentation(snapshot);
  box.append(node('span',comparison.title,'reference-position'),node('span',comparison.detail,'muted'));
  const prepared=referencePreparations.get(snapshot.session_id);
  if(viewMode==='authoritative'&&(referenceReprepareRequired(snapshot)||prepared)){
    const controls=node('div','','live-actions');
    box.append(node('p','This reference needs to be prepared again for the current analysis. We will reuse the stored audio if available; your existing session will not be retargeted.','muted'));
    if(prepared?.status==='completed'){
      box.append(node('p','Reference ready. Starting anew stops this listening session and keeps its history.','muted'));
      const start=button('Stop this session and start anew',startRepreparedSession,'secondary');start.disabled=pendingCommand||!runtimeConnected;controls.append(start);
    }else{
      const preparing=prepared?.status==='preparing',prepare=button(preparing?'Preparing reference…':'Prepare stored reference',prepareStoredReference,'secondary');
      prepare.disabled=preparing||pendingCommand||!runtimeConnected;controls.append(prepare);
      if(preparing)box.append(node('p',jobStatusText(prepared.job),'muted'));
      if(prepared?.status==='failed'){
        box.append(node('p',prepared.audioUnavailable?"We couldn't recover the original reference audio. Use Add song to select the original WAV again; the existing session is kept.":"We couldn't prepare the stored reference. Your existing session is unchanged. Try again or check Technical details.",'muted'));
        if(prepared.audioUnavailable)controls.append(button('Add song with original WAV',renderSetup,'secondary'));
      }
    }
    box.append(controls);
  }
  return box;
}
function jobStatusText(job){return job?.status==='running'?'Analyzing the stored reference…':'Reference preparation queued…';}
async function prepareStoredReference(){
  if(viewMode!=='authoritative'||!runtimeAdapter||pendingCommand)return;
  const previous=snapshot,id=previous.session_id;
  if(referencePreparations.get(id)?.status==='preparing')return;
  const state={status:'preparing',job:null};referencePreparations.set(id,state);renderConsole();
  try{
    const job=await runtimeAdapter.reprepareReference({song_id:previous.song.song_id,reference_id:previous.active_reference.reference_id,
      onProgress:job=>{state.job=job;if(page==='console'&&snapshot?.session_id===id)renderConsole();}});
    state.status='completed';state.job=job;
  }catch(error){state.status='failed';state.audioUnavailable=String(error?.payload?.error?.code??error?.message??error).includes('reference_audio_unavailable');if(page==='console'&&snapshot?.session_id===id)showError(error,'reference');}
  finally{if(page==='console'&&snapshot?.session_id===id)renderConsole();}
}
async function startRepreparedSession(){
  if(viewMode!=='authoritative'||pendingCommand)return;
  const previous=snapshot,id=previous.session_id,prepared=referencePreparations.get(id);
  if(prepared?.status!=='completed')return;
  pendingCommand=true;renderConsole();
  try{
    if(previous.capture?.state!=='stopped')await runtimeAdapter.command(commandFor(previous,'stop',{},`ui-reprepare-stop-${crypto.randomUUID()}`));
    if(snapshot?.session_id!==id||runtimeAdapter.activeSessionId!==id)return;
    await runtimeAdapter.createLiveReferenceSession({song_id:previous.song.song_id,reference_id:prepared.job.reference_id,
      source:{input_kind:previous.source.input_kind,input_asset_or_device_id:previous.source.input_asset_or_device_id},expectedSessionId:id});
    referencePreparations.delete(id);operationStatus=null;technicalDetail=null;saveCatalog(snapshot);
  }catch(error){showError(error,'reference');}
  finally{pendingCommand=false;if(page==='console')renderConsole();}
}
function renderSessionControls(){const actions=node('div','','live-actions session-controls-actions');if(viewMode!=='authoritative')return actions;if(!['SUSPENDED','STOPPED'].includes(snapshot.song.workflow_state))actions.append(guardedButton('Pause listening','pause',{},'secondary'));if(snapshot.song.workflow_state!=='STOPPED')actions.append(guardedButton('Stop session','stop',{},'ghost'));const remove=button('Delete session',()=>deleteRecentSession({session_id:snapshot.session_id,song_name:snapshot.song.name}),'delete-session');remove.disabled=sessionDeletion.pending.has(snapshot.session_id);actions.append(remove);return actions;}
function renderInterrupted(root){const ended=(snapshot.suspension_reasons??[]).includes('audio_eof'),stopped=snapshot.song.workflow_state==='STOPPED'||snapshot.capture?.state==='stopped',paused=snapshot.capture?.state==='paused',hero=node('section','','task-focus');hero.append(node('p','LISTENING','eyebrow'),node('h2',ended?'Audio finished':stopped?'Session ended':paused?'Listening is paused':'Choose a microphone to continue','panel-title'),node('p',paused?'You paused listening. Resume when the band is ready.':'Your song and uploaded reference are kept. Microphone status is shown above.','hero-copy'));if(paused)hero.append(guardedButton('Resume listening','resume',{},'primary'));else if((ended||stopped)&&!referenceReprepareRequired(snapshot)&&!referencePreparations.has(snapshot.session_id))hero.append(button('Listen with this reference',openReferenceSession,'primary'));root.append(hero);}
function renderInstrumentGrid(){
  const now=Date.now(),grid=node('section','','instrument-grid live-grid'),connected=viewMode==='fixture'||runtimeConnected,fresh=viewMode==='fixture'||currentReceiptFresh(now);
  for(const p of snapshot.perception??[]){
    const options={connected,fresh,switchPending:Boolean(sourceSwitchPending)},value=perceptionPresentation(snapshot,p,options),hint=adjustmentHintPresentation(snapshot,p,{...options,hintDeadlineMs:hintDeadlines.deadline(snapshot,p),now});
    const i=snapshot.latest_frame?.instruments?.find(i=>i.instrument_id===p.instrument_id),c=node('article','',`instrument-card ${value.state}`);
    c.append(node('h3',p.family,'instrument-name'),node('p',value.label,'instrument-status'),
      node('strong',value.numeric?balanceText(i):hint?'No numerical advice':'Advice withheld','instrument-value'),
      node('p',value.numeric?'Relative to reference':value.state==='listening'?'Waiting for a complete audio observation':p.calibration_status==='uncalibrated'&&value.state!=='unavailable'?'Uncalibrated — no numerical advice':'No reliable level advice available','confidence'));
    if(value.detail)c.append(node('p',value.detail,'muted'));
    if(hint)c.append(node('h4',hint.title,'section-title'),node('p',hint.text,'listening-note'),node('p',hint.detail,'muted'));
    grid.append(c);
  }
  if(!(snapshot.perception??[]).length)grid.append(node('p','Waiting for instrument observations…','muted'));
  return grid;
}
function renderLive(root){
  const changing=Boolean(sourceSwitchPending)||snapshot.capture?.switch_result==='pending',current=currentSourceFrame(snapshot)&&(viewMode==='fixture'||currentReceiptFresh()),hero=node('section','','quiet-monitor');
  const capturing=!current&&['listening','active'].includes(snapshot.capture?.state);
  hero.append(node('p','CURRENT STATE','eyebrow'),node('h2',changing?'Changing the listening input…':current?'Listening against your reference.':capturing?'Capturing audio. Waiting for a completed analysis…':'Waiting for current audio…','panel-title'),node('p',changing?'Previous-source advice is cleared. Your reference and song remain unchanged.':current?(viewMode==='fixture'?'Illustrative states only; no audio analysis or Runtime commands.':'Instrument recognition and any advice below come from the listening service.'):'Capture activity is not a completed model result. No missing observation is treated as normal.','hero-copy'));
  root.append(hero,renderInstrumentGrid());
}
function renderActionState(root,state){
  const hero=node('section','',`task-focus action-focus ${state.toLowerCase()}`),unavailable=viewMode==='authoritative'&&(!currentSourceFrame(snapshot)||!currentReceiptFresh());
  if(state==='RECOVERED'){
    const v=snapshot.latest_verification;hero.append(node('p','VERIFIED','eyebrow'),node('h2','Back in range','panel-title'),node('p',viewMode==='fixture'?'Illustrative verification result — not evidence from real audio.':'Fresh audio confirms the adjustment. Your uploaded reference is unchanged.','hero-copy'));
    if(v.source_observable&&typeof v.before_balance_db==='number'&&typeof v.after_balance_db==='number')hero.append(node('p',`${v.instrument_id} · ${v.before_balance_db.toFixed(1)} dB before → ${v.after_balance_db.toFixed(1)} dB after`,'verification-values'));
    hero.append(button('Return to monitoring',()=>{acknowledgedRecovery=`${sourceIdentity(snapshot)}:${recoveryKey(snapshot)}`;renderConsole();},'primary large'));
  }else if(state==='VERIFYING'){
    const value=verificationCopy(snapshot,verificationRequestedFor);
    hero.append(node('p','VERIFY THE ADJUSTMENT','eyebrow'),node('h2',value.title,'panel-title'),node('p','Only new audio captured after your adjustment can confirm the result.','hero-copy'));
    const a=snapshot.adjustment;
    if(a&&!value.listening)hero.append(guardedButton('Listen again','recheck',{adjustment_id:a.adjustment_id},'primary large'));
    if(value.listening)hero.append(node('p','Keep the band playing. We are waiting for a fresh verification result.','listening-note'));
  }else{
    const adjusting=Boolean(snapshot.adjustment),rec=snapshot.recommendations?.[0],instrument=snapshot.latest_frame?.instruments.find(i=>i.instrument_id===(rec?.instrument_id??snapshot.incident?.event?.instrument_ids?.[0]));const p=snapshot.perception?.find(p=>p.instrument_id===instrument?.instrument_id),actionable=instrument&&perceptionPresentation(snapshot,p,{connected:viewMode==='fixture'||runtimeConnected,fresh:!unavailable,switchPending:Boolean(sourceSwitchPending)}).numeric;
    hero.append(node('p',adjusting?'HUMAN ADJUSTMENT':'SUGGESTED FIX','eyebrow'),node('h2',adjusting?'Make a small adjustment.':'A balance change needs attention.','panel-title'));
    if(instrument)hero.append(node('p',instrument.family,'section-title'),node('strong',actionable?balanceText(instrument):'Balance unavailable','live-figure'),node('p','Relative to the uploaded reference','muted'),node('p',conciseConfidence(instrument.confidence),'muted'));
    if(rec&&actionable){const fix=node('section','','suggested-fix');const numeric=typeof rec.suggested_step_db==='number';fix.append(node('h3',numeric?`${rec.suggested_step_db<0?'Reduce':'Raise'} approximately ${Math.abs(rec.suggested_step_db)} dB`:'Adjust conservatively','recommendation'),node('p',rec.human_control_hint??'Make a small manual correction, then listen again.','muted'));hero.append(fix);}
    if(viewMode==='authoritative')hero.append(adjusting?guardedButton("I've adjusted",'complete_adjustment',{adjustment_id:snapshot.adjustment.adjustment_id},'primary large'):guardedButton('Start adjustment','start_adjustment',{},'primary large'));
    else hero.append(node('p','Illustrative example — no mixer or Runtime commands are sent.','muted'));
  }
  root.append(hero,disclosure('Current instrument observations','action-observations',renderInstrumentGrid(null,unavailable)));
}
async function sendCommand(action,payload){if(viewMode!=='authoritative'||pendingCommand)return null;const guard=commandGuard(action,viewMode,runtimeAdapter,snapshot,runtimeConnected,receiptMs,Date.now(),resultDeadlines.deadline(snapshot));if(!guard.allowed){statusMessage(productError(guard.reason));return null;}const c=commandFor(snapshot,action,payload,`ui-${action}-${crypto.randomUUID()}`);const verificationBefore=snapshot.latest_verification?.verification_id??'none';operationStatus=null;technicalDetail=null;pendingCommand=true;renderConsole();try{const response=await runtimeAdapter.command(c);if(action==='recheck')verificationRequestedFor=`${c.session_id}:${payload.adjustment_id}:${verificationBefore}`;return response;}catch(e){showError(e);return null;}finally{pendingCommand=false;if(page==='console')renderConsole();}}
function getCatalog(){try{return typeof localStorage==='undefined'?[]:normalizeCatalogRows(JSON.parse(localStorage.getItem(CATALOG_KEY)||'[]')).filter(row=>!runtimeAdapter?.deletedSessionIds.has(row.session_id));}catch{return[];}}

async function start(){const adapter=new RuntimeAdapter({onSnapshot:setSnapshot,onStatus:text=>{if(/unavailable|disconnected|failed/.test(text))showError(text);else if(technicalDetail&&/event stream|reconnect/.test(technicalDetail)){operationStatus=null;technicalDetail=null;}},onSessionUnavailable:id=>{clearSessionView(id);statusMessage('This session is no longer available. Choose another session or prepare a song.');},onConnection:(connected,state)=>{runtimeConnected=connected;runtimeConnectionState=state??(connected?'active':'disconnected');if(page==='console'&&snapshot&&viewMode==='authoritative')renderConsole();}});try{runtimeHealth=await adapter.health();deviceDiscovery=await adapter.audioDevices();runtimeAdapter=adapter;runtimeStartupError=null;viewMode='authoritative';}catch(e){runtimeHealth=null;runtimeStartupError=e;runtimeConnectionState='error';viewMode='fixture';}try{fixtures=await (await fetch(FIXTURE_PATH)).json();}catch{fixtures=null;}renderSelection();}

if(typeof document!=='undefined')start().catch(e=>{app().replaceChildren(node('p',productError(e)));});
