import copy
import hashlib
import json
import tempfile
import unittest
import wave
from pathlib import Path

import numpy as np

from benchmarks.validate_multitrack_assets import validate_assets
from training.controlled_pairs import PairSpec, generate_controlled_pair
from training.multitrack_assets import (
    load_recording_excerpt,
    sha256_file,
    validate_manifest,
)


class MultitrackAssetTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        (self.root / "take-1").mkdir()
        self.rate = 8000
        self.count = 800
        time = np.arange(self.count, dtype=np.float64) / self.rate
        self.signals = {
            "bass": 0.25 * np.sin(2 * np.pi * 100 * time),
            "guitar": 0.20 * np.sin(2 * np.pi * 500 * time),
        }
        stems = []
        for instrument_id, signal in self.signals.items():
            path = self.root / "take-1" / f"{instrument_id}.wav"
            self._write_pcm16(path, signal)
            stems.append({
                "instrument_id": instrument_id,
                "family": instrument_id,
                "relative_path": f"take-1/{instrument_id}.wav",
                "sha256": sha256_file(path),
            })
        self.manifest = {
            "schema_version": "1.0",
            "dataset_id": "unit-test-multitrack-v1",
            "provenance": {
                "origin": "generated unit-test tones",
                "license_or_permission": "generated by repository test",
                "attribution": None,
                "allowed_publication_status": "publishable",
            },
            "recordings": [{
                "recording_id": "take-1",
                "parent_group_id": "song-1",
                "split": "test",
                "sample_rate_hz": self.rate,
                "sample_count": self.count,
                "stems": stems,
            }],
        }

    def tearDown(self):
        self.temp.cleanup()

    @staticmethod
    def _write_pcm16(path: Path, signal: np.ndarray) -> None:
        pcm = np.round(np.clip(signal, -1.0, 1.0 - 1 / 32768) * 32768).astype("<i2")
        with wave.open(str(path), "wb") as wav:
            wav.setnchannels(1)
            wav.setsampwidth(2)
            wav.setframerate(8000)
            wav.writeframes(pcm.tobytes())

    def test_verified_excerpt_feeds_deterministic_pair_generator(self):
        loaded = load_recording_excerpt(
            self.manifest,
            dataset_root=self.root,
            recording_id="take-1",
            sample_start=100,
            sample_count=400,
        )
        self.assertEqual("test", loaded.split)
        self.assertEqual({"bass", "guitar"}, set(loaded.stems))
        pair = generate_controlled_pair(
            loaded.stems,
            PairSpec(
                pair_id="take-1-excerpt-100-500",
                split_id=f"{loaded.dataset_id}:{loaded.split}",
                seed=42,
                source_injected_gain_db={"bass": 0.0, "guitar": 4.0},
            ),
            asset_provenance=loaded.asset_provenance,
        )
        self.assertEqual("take-1", pair.metadata["asset_provenance"]["recording_id"])
        self.assertEqual(4.0, pair.labels.raw_source_delta_db["guitar"])
        self.assertEqual(2, len(pair.metadata["asset_provenance"]["verified_assets"]))

    def test_parent_group_cannot_cross_splits(self):
        bad = copy.deepcopy(self.manifest)
        duplicate = copy.deepcopy(bad["recordings"][0])
        duplicate.update(recording_id="take-2", split="train")
        bad["recordings"].append(duplicate)
        with self.assertRaisesRegex(ValueError, "Split leakage"):
            validate_manifest(bad)

    def test_unsafe_relative_path_is_rejected_before_file_access(self):
        bad = copy.deepcopy(self.manifest)
        bad["recordings"][0]["stems"][0]["relative_path"] = "../outside.wav"
        with self.assertRaisesRegex(ValueError, "Unsafe"):
            validate_manifest(bad)

    def test_hash_mismatch_is_rejected(self):
        bad = copy.deepcopy(self.manifest)
        bad["recordings"][0]["stems"][0]["sha256"] = "0" * 64
        with self.assertRaisesRegex(ValueError, "SHA-256 mismatch"):
            load_recording_excerpt(
                bad,
                dataset_root=self.root,
                recording_id="take-1",
                sample_start=0,
                sample_count=100,
            )

    def test_header_sample_count_mismatch_is_rejected(self):
        bad = copy.deepcopy(self.manifest)
        bad["recordings"][0]["sample_count"] += 1
        with self.assertRaisesRegex(ValueError, "Sample-count mismatch"):
            load_recording_excerpt(
                bad,
                dataset_root=self.root,
                recording_id="take-1",
                sample_start=0,
                sample_count=100,
            )

    def test_validation_report_records_manifest_hash_and_split(self):
        manifest_path = self.root / "manifest.json"
        manifest_path.write_text(json.dumps(self.manifest), encoding="utf-8")
        report = validate_assets(manifest_path, self.root)
        self.assertEqual("valid", report["status"])
        self.assertEqual({"test": 1}, report["split_counts"])
        self.assertEqual(sha256_file(manifest_path), report["manifest_sha256"])
        self.assertEqual(2, report["recordings"][0]["verified_stem_count"])


if __name__ == "__main__":
    unittest.main()
