import copy
import hashlib
import json
import tempfile
import unittest
import wave
from pathlib import Path

import numpy as np

from training.multitrack_assets import sha256_file
from training.pair_plan import (
    build_pair_plan,
    materialize_planned_pair,
    validate_pair_plan_config,
)


class PairPlanTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.dataset_root = self.root / "dataset"
        self.dataset_root.mkdir()
        self.rate = 8000
        self.count = 800
        recordings = []
        for split, recording_id, parent_id in (
            ("train", "take-train", "song-train"),
            ("test", "take-test", "song-test"),
        ):
            folder = self.dataset_root / recording_id
            folder.mkdir()
            stems = []
            time = np.arange(self.count, dtype=np.float64) / self.rate
            signals = {
                "bass": 0.2 * np.sin(2 * np.pi * 100 * time),
                "guitar": 0.2 * np.sin(2 * np.pi * 500 * time),
            }
            if split == "test":
                signals["guitar"] = np.zeros_like(time)
            for instrument_id, signal in signals.items():
                relative = f"{recording_id}/{instrument_id}.wav"
                path = self.dataset_root / relative
                self._write_pcm16(path, signal)
                stems.append({
                    "instrument_id": instrument_id,
                    "family": instrument_id,
                    "relative_path": relative,
                    "sha256": sha256_file(path),
                })
            recordings.append({
                "recording_id": recording_id,
                "parent_group_id": parent_id,
                "split": split,
                "sample_rate_hz": self.rate,
                "sample_count": self.count,
                "stems": stems,
            })
        self.manifest = {
            "schema_version": "1.0",
            "dataset_id": "pair-plan-fixture-v1",
            "provenance": {
                "origin": "generated test tones",
                "license_or_permission": "generated by repository test",
                "attribution": None,
                "allowed_publication_status": "publishable",
            },
            "recordings": recordings,
        }
        self.config = {
            "schema_version": "1.0",
            "config_id": "unit-pair-plan-v1",
            "root_seed": 17,
            "splits": ["train", "test"],
            "excerpt_duration_s": 0.05,
            "hop_duration_s": 0.05,
            "max_excerpts_per_recording": 1,
            "shared_scale": 0.25,
            "single_source_gain_grid_db": [-4, 4],
            "common_gain_grid_db": [4],
            "multi_source_gain_cycles_db": [[-2, 4]],
            "noise_profiles": [
                {"kind": "none", "reference_snr_db": None, "observation_snr_db": None},
                {"kind": "white_gaussian", "reference_snr_db": 20, "observation_snr_db": 10},
            ],
        }
        self.manifest_path = self.root / "manifest.json"
        self.config_path = self.root / "config.json"
        self.manifest_path.write_text(json.dumps(self.manifest), encoding="utf-8")
        self.config_path.write_text(json.dumps(self.config), encoding="utf-8")

    def tearDown(self):
        self.temp.cleanup()

    @staticmethod
    def _write_pcm16(path: Path, signal: np.ndarray) -> None:
        pcm = np.round(np.clip(signal, -1.0, 1.0 - 1 / 32768) * 32768).astype("<i2")
        with wave.open(str(path), "wb") as wav:
            wav.setnchannels(1)
            wav.setsampwidth(2)
            wav.setframerate(8000)
            wav.writeframes(pcm.tobytes())

    def _build(self):
        return build_pair_plan(self.manifest_path, self.config_path, git_commit="a" * 40)

    def test_plan_is_semantically_deterministic_and_grouped(self):
        first = self._build()
        second = self._build()
        self.assertEqual(first["pairs"], second["pairs"])
        # Per excerpt: zero + one common + four single-source + one multi; two noises.
        self.assertEqual(28, first["pair_count"])
        self.assertEqual(["song-test"], first["split_identity"]["test"]["parent_group_ids"])
        self.assertEqual(["song-train"], first["split_identity"]["train"]["parent_group_ids"])
        self.assertEqual(len({item["pair_id"] for item in first["pairs"]}), 28)
        self.assertEqual(len({item["seed"] for item in first["pairs"]}), 28)

    def test_config_or_manifest_byte_change_changes_recorded_hash(self):
        first = self._build()
        self.config_path.write_text(json.dumps(self.config, indent=2), encoding="utf-8")
        second = self._build()
        self.assertNotEqual(first["config_sha256"], second["config_sha256"])
        self.assertEqual(first["pairs"], second["pairs"])

    def test_materialization_verifies_plan_and_masks_silent_source(self):
        plan = self._build()
        entry = next(item for item in plan["pairs"] if (
            item["recording_id"] == "take-test"
            and item["scenario_id"] == "one_source_guitar_+4db"
            and item["noise"]["kind"] == "none"
        ))
        pair = materialize_planned_pair(
            self.manifest_path, self.dataset_root, plan, entry
        )
        self.assertFalse(pair.labels.valid_source_mask["guitar"])
        self.assertIsNone(pair.labels.raw_source_delta_db["guitar"])
        self.assertEqual("one_source_gain", pair.metadata["pair_plan"]["scenario_kind"])

    def test_materialization_rejects_manifest_drift(self):
        plan = self._build()
        changed = copy.deepcopy(self.manifest)
        changed["provenance"]["origin"] = "changed provenance"
        self.manifest_path.write_text(json.dumps(changed), encoding="utf-8")
        with self.assertRaisesRegex(ValueError, "Manifest hash"):
            materialize_planned_pair(
                self.manifest_path, self.dataset_root, plan, plan["pairs"][0]
            )

    def test_invalid_noise_and_missing_split_are_rejected(self):
        bad = copy.deepcopy(self.config)
        bad["noise_profiles"] = [{
            "kind": "none", "reference_snr_db": 20, "observation_snr_db": None
        }]
        with self.assertRaisesRegex(ValueError, "Clean noise"):
            validate_pair_plan_config(bad)
        bad = copy.deepcopy(self.config)
        bad["splits"].append("calibration")
        self.config_path.write_text(json.dumps(bad), encoding="utf-8")
        with self.assertRaisesRegex(ValueError, "lacks requested splits"):
            build_pair_plan(self.manifest_path, self.config_path, git_commit="a" * 40)


if __name__ == "__main__":
    unittest.main()
